/*
 * Date:	2003/10/01
 *
 * Author:	N.Fukuyasu (Generated by 'mkverstr')
 *
 * $Id: Version.java,v 1.20 2006/06/21 10:33:12 fukuyasu Exp $
 *
 * Copyright (C) 2003-2006 The Plasmin Project. All rights reserved.
 */

package plasmin;

public class Version {
	private static final String major_v = "3";
	private static final String minor_v = "3.4";

	public static String getMajorVersion() {
		return major_v;
	}

	public static String getMinorVersion() {
		return minor_v;
	}
}
